name: Best Practice
description: Submit a best practice for the Northeast COE Site
title: "Best Practice Submission"
labels: ["best-practices"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your best practice!
  - type: input
    id: title
    attributes:
      label: Title
      description: Brief title for this best practice
      placeholder: ex. Don't dispose HttpClient in C#
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Who gets credit?
      placeholder: ex. Microsoft
    validations:
      required: true      
  - type: input
    id: tags
    attributes:
      label: tags
      description: Comma-separated list of tags
      placeholder: ex. c#, httpclient
    validations:
      required: false     
  - type: input
    id: image
    attributes:
      label: Image
      description: Enter a fully qualified URL to a public image that will be used on the content
      placeholder: ex. http://www.microsoft.com/images/synapse_logo.jpg
    validations:
      required: false        
  - type: textarea
    id: body
    attributes:
      label: Best Practice
      description: Enter markdown-compatible text
      placeholder: 
    validations:
      required: true               
