name: Best Practices Issue Workflow
on:
  issues:
    types:
      - labeled
jobs:
  get-issue-info:
    if: github.event.label.name == 'best-practices'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    env:
      FILENAME: ${{ github.event.issue.number }}
      BODY: "${{ github.event.issue.body }} "
      PRBODY: "REVIEW CHANGES FOR #${{ github.event.issue.number }}. Closes #${{ github.event.issue.number }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create branch
        run: |
          git checkout -b newcontent-${{env.FILENAME}}
      - name: Create file
        run:  |
          cd _solutions
          $content = "${{env.BODY}}"
          $title, $author, $tags, $image, $bp = ($content -split "\n\n")[1,3,5,7,9]
          $date = Get-Date -UFormat "%F"
          $issuetitle = $title -replace " ",""
          $filename = $date + "-" + $issuetitle
          New-item -Path . -Name "$filename.md"
          "---" >> "$filename.md"
          "title: $title" >> "$filename.md"
          "author: $author" >> "$filename.md"
          "categories: best-practices" >> "$filename.md"
          "tags: [$tags]" >> "$filename.md"
          "description: $description" >> "$filename.md"
          "image: $image" >> "$filename.md"
          "---" >> "$filename.md"
          "$bp" >> "$filename.md"
        shell: pwsh
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: stage changes
        run: git add .
      - name: commit changes
        run: |
          git commit -m "adding new file"
          git push -u origin newcontent-${{env.FILENAME}}
      - name: push new file
        run: gh pr create --title "New BEST PRACTICE Content Submission ${{env.FILENAME}}" --body "${{env.PRBODY}}" --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
